# Generated by Django 6.1.1 on 2026-10-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='debug_code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
